# Generated by Django 4.2.7 on 2023-11-22 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import energy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArtefacto', models.CharField(max_length=20)),
                ('consumoKwH', models.FloatField(default=0)),
                ('horasDeUso', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('consumoKwH', models.FloatField(default=0)),
                ('horasDeUso', models.FloatField(default=0)),
                ('cantidadArtefactos', models.IntegerField()),
                ('consumoTotalPorArtefacto', models.FloatField(default=0)),
                ('aartefacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.artefactos')),
            ],
        ),
    ]
