# Generated by Django 4.2.7 on 2023-11-22 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='aartefacto',
            new_name='artefacto',
        ),
    ]
