# Generated by Django 4.2.7 on 2023-11-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_rename_aartefacto_inventario_artefacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='consumoKwH',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='horasDeUso',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='artefacto',
        ),
        migrations.AddField(
            model_name='inventario',
            name='artefacto',
            field=models.ManyToManyField(to='energy.artefactos'),
        ),
    ]
