# Generated by Django 4.2.7 on 2023-11-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_remove_inventario_consumokwh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='consumoTotal',
            field=models.FloatField(default=0),
        ),
    ]
