# Generated by Django 4.2.7 on 2023-11-23 01:12

from django.db import migrations, models
import energy.models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0004_alter_inventario_consumototal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='consumoTotal',
            field=models.FloatField(default=energy.models.Inventario.CalcularConsumoTotal),
        ),
    ]
