# Generated by Django 4.2.7 on 2024-02-19 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("energy", "0005_perfil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="imagen",
            field=models.ImageField(default="default.jpg", upload_to="profile_images/"),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
