# Generated by Django 4.2.7 on 2023-11-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0005_alter_inventario_consumototal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='consumoTotal',
            field=models.FloatField(default=0),
        ),
    ]
