# Generated by Django 4.2.7 on 2024-02-19 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("energy", "0006_alter_perfil_imagen_alter_perfil_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
