# Generated by Django 4.2.7 on 2024-02-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0007_alter_perfil_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="imagen",
            field=models.ImageField(default="default.jpg", upload_to="media/"),
        ),
    ]
