# Generated by Django 4.2.7 on 2024-02-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0009_alter_perfil_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="imagen",
            field=models.ImageField(
                default="media/default.jpg", upload_to="static/media/profile_images"
            ),
        ),
    ]
