# Generated by Django 4.2.7 on 2023-11-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0011_alter_inventario_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='dia',
            field=models.DateField(default=23),
        ),
    ]
