# Generated by Django 4.2.7 on 2024-02-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0013_alter_perfil_user_alter_perfil_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artefacto",
            name="consumo_wh",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
