# Generated by Django 4.2.7 on 2024-02-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0016_alter_artefacto_consumo_wh"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artefacto",
            name="horas_de_uso",
            field=models.FloatField(default=0),
        ),
    ]
