# Generated by Django 4.2.7 on 2023-11-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0018_inventario_consumototal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='dia',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
