# Generated by Django 4.2.7 on 2024-02-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0018_alter_inventario_cantidad_artefacto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artefacto",
            name="nombre_artefacto",
            field=models.CharField(max_length=50),
        ),
    ]
