# Generated by Django 4.2.7 on 2023-11-23 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0019_alter_inventario_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='user',
        ),
    ]
