# Generated by Django 4.2.7 on 2023-11-23 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0022_inventario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='consumoTotal',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='consumoTotalPorArtefacto',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='nombre',
        ),
    ]
