# Generated by Django 4.2.7 on 2023-11-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0023_remove_inventario_consumototal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='consumoTotal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inventario',
            name='consumoTotalPorArtefacto',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inventario',
            name='nombre',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
