# Generated by Django 4.2.7 on 2023-11-25 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0024_inventario_consumototal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='artefacto',
        ),
        migrations.AddField(
            model_name='artefactos',
            name='inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.inventario'),
        ),
    ]
