# Generated by Django 4.2.7 on 2023-11-25 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0025_remove_inventario_artefacto_artefactos_inventario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='nombre',
        ),
    ]
