# Generated by Django 4.2.7 on 2023-11-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0026_remove_inventario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='nombre',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
