# Generated by Django 4.2.7 on 2023-11-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0028_rename_consumototalporartefacto_inventario_consumoartefacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='horasDeUso',
            field=models.IntegerField(default=0),
        ),
    ]
