# Generated by Django 4.2.7 on 2023-11-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0030_remove_inventario_consumoartefacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='consumoArtefacto',
            field=models.FloatField(default=0),
        ),
    ]
