# Generated by Django 4.2.7 on 2023-11-26 03:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('energy', '0031_inventario_consumoartefacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='consumosDiarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(default=datetime.datetime.now)),
                ('consumoTotal', models.FloatField(default=0)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.inventario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
