# Generated by Django 4.2.7 on 2023-11-26 03:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('energy', '0032_consumosdiarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='consumosDiarios',
            new_name='consumoDiario',
        ),
    ]
