# Generated by Django 4.2.7 on 2023-11-26 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0034_rename_consumodiario_consumodiariomensual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumodiariomensual',
            name='inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='energy.inventario'),
        ),
    ]
