# Generated by Django 4.2.7 on 2023-11-26 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0035_alter_consumodiariomensual_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumodiariomensual',
            name='consumoTotalMensual',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='consumodiariomensual',
            name='inventario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='energy.inventario'),
        ),
    ]
