# Generated by Django 4.2.7 on 2023-11-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0036_consumodiariomensual_consumototalmensual_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumodiariomensual',
            old_name='consumoTotalMensual',
            new_name='consumoTotalDelMes',
        ),
        migrations.AddField(
            model_name='inventario',
            name='consumoTotalDelMes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='consumodiariomensual',
            name='dia',
            field=models.DateField(auto_now_add=True),
        ),
    ]
