# Generated by Django 4.2.7 on 2023-11-26 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0037_rename_consumototalmensual_consumodiariomensual_consumototaldelmes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumodiariomensual',
            old_name='consumoTotalDelMes',
            new_name='consumoTotalMensual',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='consumoTotalDelMes',
        ),
    ]
