# Generated by Django 4.2.7 on 2023-12-02 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0038_rename_consumototaldelmes_consumodiariomensual_consumototalmensual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefactos',
            name='inventario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artefacto_list', to='energy.inventario'),
        ),
    ]
