# Generated by Django 4.2.7 on 2023-12-02 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0039_alter_artefactos_inventario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artefactos',
            name='inventario',
        ),
        migrations.AddField(
            model_name='inventario',
            name='artefacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario', to='energy.artefactos'),
        ),
    ]
