# Generated by Django 4.2.7 on 2023-12-04 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('energy', '0040_remove_artefactos_inventario_inventario_artefacto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsumoDiarioMensual',
            new_name='Informe',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='inventario',
            name='nombreArtefacto',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
