# Generated by Django 4.2.7 on 2023-12-04 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0041_rename_consumodiariomensual_informe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='artefacto',
        ),
        migrations.AddField(
            model_name='artefactos',
            name='inventario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artefsactoList', to='energy.inventario'),
        ),
    ]
