# Generated by Django 4.2.7 on 2023-12-13 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("energy", "0043_remove_artefactos_consumokwh_artefactos_consumowh_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artefactos",
            name="inventario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="artefsactoList",
                to="energy.inventario",
            ),
        ),
        migrations.AlterField(
            model_name="artefactos",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
