# Generated by Django 4.2.7 on 2023-12-09 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0043_alter_artefactos_horasdeuso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefactos',
            name='consumoKwH',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='informe',
            name='consumoTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='informe',
            name='consumoTotalMensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidadArtefactos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='consumoArtefacto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='consumoTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
