# Generated by Django 4.2.7 on 2023-12-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0044_alter_artefactos_consumokwh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefactos',
            name='consumoKwH',
            field=models.PositiveBigIntegerField(default=0.0),
        ),
    ]
