# Generated by Django 4.2.7 on 2023-12-13 18:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0046_remove_inventario_nombreartefacto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventario",
            name="horasDeUso",
        ),
    ]
