# Generated by Django 4.2.7 on 2023-12-13 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0047_remove_inventario_horasdeuso"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="informe",
            name="inventario",
        ),
        migrations.AddField(
            model_name="inventario",
            name="informe",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventario",
                to="energy.informe",
            ),
        ),
    ]
