# Generated by Django 4.2.7 on 2023-12-13 23:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0050_alter_artefactos_user_alter_informe_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="informe",
            name="consumoTotal",
        ),
        migrations.RemoveField(
            model_name="informe",
            name="dia",
        ),
    ]
