# Generated by Django 4.2.7 on 2023-12-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0051_remove_informe_consumototal_remove_informe_dia"),
    ]

    operations = [
        migrations.AddField(
            model_name="informe",
            name="consumoTotal",
            field=models.FloatField(default=0),
        ),
    ]
