# Generated by Django 4.2.7 on 2023-12-14 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0052_informe_consumototal"),
    ]

    operations = [
        migrations.AddField(
            model_name="informe",
            name="dia",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
