# Generated by Django 4.2.7 on 2023-12-14 01:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0058_alter_informe_inventario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="informe",
            name="consumoTotal",
        ),
    ]
