# Generated by Django 4.2.7 on 2023-12-15 03:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("energy", "0060_remove_inventario_consumototal_informe_consumototal"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Artefactos",
            new_name="Artefacto",
        ),
        migrations.RenameField(
            model_name="inventario",
            old_name="cantidadArtefactos",
            new_name="cantidadArtefacto",
        ),
    ]
