# Generated by Django 4.2.7 on 2023-12-15 03:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0061_rename_artefactos_artefacto_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artefacto",
            old_name="consumoWH",
            new_name="consumo_wh",
        ),
        migrations.RenameField(
            model_name="artefacto",
            old_name="horasDeUso",
            new_name="horas_de_uso",
        ),
        migrations.RenameField(
            model_name="artefacto",
            old_name="nombreArtefacto",
            new_name="nombre_artefacto",
        ),
        migrations.RenameField(
            model_name="informe",
            old_name="consumoTotal",
            new_name="consumo_total",
        ),
        migrations.RenameField(
            model_name="informe",
            old_name="consumoTotalMensual",
            new_name="consumototal_mensual",
        ),
        migrations.RenameField(
            model_name="inventario",
            old_name="cantidadArtefacto",
            new_name="cantidad_artefacto",
        ),
        migrations.RenameField(
            model_name="inventario",
            old_name="consumoArtefacto",
            new_name="consumo_artefacto",
        ),
    ]
